version: '3.8'

services:
  # Ollama Service (for local embeddings)
  ollama:
    image: ollama/ollama:latest
    container_name: study-app-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - study-app-network
    # Pull the embedding model on startup
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        /bin/ollama serve &
        sleep 5
        ollama pull nomic-embed-text
        wait

  # Python AI Service (FastAPI)
  ai-service:
    build:
      context: ./ai-service-python
      dockerfile: Dockerfile
    container_name: study-app-ai-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ./ai-service-python:/app
      - ai_vector_store:/app/vector_store
    depends_on:
      - ollama
    networks:
      - study-app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Node.js Backend
  backend:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    container_name: study-app-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      - JWT_EXPIRE=${JWT_EXPIRE:-7d}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - AI_SERVICE_URL=http://ai-service:8000
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    volumes:
      - ./backend-node:/app
      - /app/node_modules
    depends_on:
      - ai-service
    networks:
      - study-app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama_data:
    driver: local
  ai_vector_store:
    driver: local

networks:
  study-app-network:
    driver: bridge
